version: "3.9"
   
services:
  main:
    build: .
    environment:
      DATABASE_URL : postgres://postgres:psqladmin@db/carwow_v1
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    ports:
      - 4000:5432
    environment:
      - POSTGRES_NAME=CarWow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psqladmin
    volumes:
      - ../pgdata:/var/lib/postgresql/data