# Generated by Django 4.0.4 on 2022-09-21 14:15

import car.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_name', models.CharField(max_length=50)),
                ('year_begin', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), car.models.max_value_current_year])),
                ('year_end', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), car.models.max_value_current_year])),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=50)),
                ('transmission', models.CharField(choices=[('Manual', 'MANUAL'), ('Automatic', 'AUTOMATIC'), ('Electric', 'ELECTRIC')], default='Automatic', max_length=10)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'PETROL'), ('Diesel', 'DIESEL'), ('Electric', 'ELECTRIC')], default='Petrol', max_length=10)),
                ('body_type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'SEDAN'), ('Hatchback', 'HATCHBACK'), ('Wagon', 'WAGON'), ('MPV', 'MPV')], default='Sedan', max_length=10)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='car.generation')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car.brand')),
            ],
        ),
        migrations.AddField(
            model_name='generation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='car.model'),
        ),
    ]
