# Generated by Django 4.0.4 on 2022-11-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='image',
            field=models.FilePathField(blank=True, max_length=500, null=True, path='https://storage.googleapis.com/vehicle-media/'),
        ),
    ]
