# Generated by Django 4.0.4 on 2022-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_variant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
