# Generated by Django 4.0.4 on 2022-11-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_carsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsuggestion',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='carsuggestion',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='carsuggestion',
            name='transmission',
        ),
    ]
