# Generated by Django 4.0.4 on 2022-11-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_remove_carsuggestion_body_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsuggestion',
            name='body_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'SEDAN'), ('Hatchback', 'HATCHBACK'), ('Wagon', 'WAGON'), ('MPV', 'MPV'), ('Pickup Truck', 'PICKUP TRUCK'), ('Coupe', 'COUPE'), ('Convertible', 'CONVERTIBLE')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
